### ISSUE TITLE
V8 version: v6.8.199 producing http 403 

### ISSUE THREAD

**Issue by rwaldron** [GoogleChromeLabs/jsvu#40]
```
✔ Found latest V8 version: v6.8.199.
✔ URL: https://storage.googleapis.com/chromium-v8/official/canary/v8-mac64-rel-6.8.199.zip
❯ Downloading…
  [========================================================================] 100%
✖ HTTPError: Response code 403 (Forbidden)
```

A quick reality check of https://storage.googleapis.com/chromium-v8/official/canary/v8-mac64-rel-6.8.199.zip reveals: 

```
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
  <Code>AccessDenied</Code>
  <Message>Access denied.</Message>
  <Details>
    Anonymous caller does not have storage.objects.get access to chromium-v8/official/canary/v8-mac64-rel-6.8.199.zip.
  </Details>
</Error>
```

**Comment by rwaldron** [comment]
Same is happening with v6.8.204

**Comment by mathiasbynens** [comment]
Are you using jsvu v1.2.2? This sounds similar to #35.

**Comment by rwaldron** [comment]
Updating produces... 

```
$ jsvu
📦 jsvu v1.2.2 — the JavaScript engine Version Updater 📦
✔ Read OS from config: mac64
✔ Read engines from config: chakra, javascriptcore, spidermonkey, v8, xs
✔ Found latest Chakra version: v1.8.4.
✖ Chakra v1.8.4 is already installed.
✔ Found latest JavaScriptCore version: v231167.
✖ JavaScriptCore v231167 is already installed.
✔ Found latest SpiderMonkey version: v61.0b4.
✖ SpiderMonkey v61.0b4 is already installed.
✔ Found latest V8 version: v6.8.192.
✔ URL: https://storage.googleapis.com/chromium-v8/official/canary/v8-mac64-rel-6.8.192.zip
✔ Download completed.
❯ Extracting…
Installing library to ~/.jsvu/engines/v8/icudtl.dat…
Installing library to ~/.jsvu/engines/v8/natives_blob.bin…
Installing library to ~/.jsvu/engines/v8/snapshot_blob.bin…
Installing binary to ~/.jsvu/engines/v8/v8…
Installing wrapper script to ~/.jsvu/v8…
(node:41373) UnhandledPromiseRejectionWarning: TypeError: generateScript(...).trimStart is not a function
    at Installer.installScript (/usr/local/lib/node_modules/jsvu/shared/installer.js:133:5)
    at Promise (/usr/local/lib/node_modules/jsvu/engines/v8/extract.js:53:14)
    at <anonymous>
(node:41373) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:41373) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Using node v8.11.1

**Comment by mathiasbynens** [comment]
Node.js v10 is now required. Does that help?

**Comment by rwaldron** [comment]
@mathiasbynens any particular reason why you're **requiring** a not-yet-LTS version of Node? Node 10 isn't LTS until October. I will suffer through remembering to `nvm use 10` every time I need to update JS engines, but it would be great to at least know why I'm doing that :P

**Comment by mathiasbynens** [comment]
No reason other than I like to use modern JS features as they become available. That said, I want jsvu to be useful for your use case. I had no idea you run Node.js LTS by default, and I’d be okay with following LTS for jsvu if that helps you.

**Comment by rwaldron** [comment]
@mathiasbynens you're the coolest—thanks <3
