### ISSUE TITLE
ENOENT while installing quickjs

### ISSUE THREAD

**Issue by nicolo-ribaudo** [GoogleChromeLabs/jsvu#87]
When I run `jsvu`, I get this error:

```
✔ Found latest QuickJS version: v2020-01-05.
✔ URL: https://bellard.org/quickjs/binary_releases/quickjs-linux-x86_64-2020-01-05.zip
✔ Download completed.
❯ Extracting…
Installing binary to ~/.jsvu/engines/quickjs/quickjs…
(node:8766) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, stat '/tmp/cc217509360b4631d3162c027c25b57c/qjsbn'
    at Object.statSync (fs.js:947:3)
    at Object.statSync (/home/nicolo/.config/yarn/global/node_modules/graceful-fs/polyfills.js:307:34)
    at getStatsSync (/home/nicolo/.config/yarn/global/node_modules/jsvu/node_modules/fs-extra/lib/util/stat.js:58:18)
    at Object.checkPathsSync (/home/nicolo/.config/yarn/global/node_modules/jsvu/node_modules/fs-extra/lib/util/stat.js:90:33)
    at Object.moveSync (/home/nicolo/.config/yarn/global/node_modules/jsvu/node_modules/fs-extra/lib/move-sync/move-sync.js:14:28)
    at installSingleBinary (/home/nicolo/.config/yarn/global/node_modules/jsvu/shared/installer.js:30:6)
    at Installer.installBinary (/home/nicolo/.config/yarn/global/node_modules/jsvu/shared/installer.js:75:5)
    at /home/nicolo/.config/yarn/global/node_modules/jsvu/engines/quickjs/extract.js:35:15
(node:8766) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:8766) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

The contents of that temporary directory are
```
➜ ls /tmp/cc217509360b4631d3162c027c25b57c/
jsvutmpf      qjs*          run-test262*
```

OS: Linux 64 bit

Maybe the contents of the QuickJS archive changed recently?

**Comment by mathiasbynens** [comment]
I've pinged Fabrice about this.

**Comment by mathiasbynens** [comment]
Fabrice's response:

> Sorry, I forgot it could cause a problem. `qjsbn` and `run-test262-bn` were
> suppressed because they are now integrated in `qjs` and `run-test262`.

So, it'd be best to change the logic as follows: if `qjsbn` is present in the ZIP, install that. Else, install `qjs`. (This ensures that installing older QuickJS versions still works as before.) Patches welcome!

**Comment by mathiasbynens** [comment]
Alternatively, simply assume modern behavior, and just install `qjs`. This means that anyone explicitly installing an older `quickjs` version would not get `BigInt` support anymore (whereas with current jsvu, they would), but that might not be the end of the world given `quickjs` releases are not tied to a browser (and thus installing older versions does not seem as useful).

**Comment by mathiasbynens** [comment]
I've went with the latter approach.
