### ISSUE TITLE
hermes@0.6.0 broke jsvu

### ISSUE THREAD

**Issue by mathiasbynens** [GoogleChromeLabs/jsvu#96]
Looks like the Hermes team changed something about the way they publish new releases, causing jsvu to break:

```
$ jsvu hermes@0.6.0
📦 jsvu v1.11.2 — the JavaScript engine Version Updater 📦
✔ Read OS from config: mac64
✔ Read engine + version from CLI argument: hermes v0.6.0
✔ Found specific Hermes version: v0.6.0.
✔ URL: https://github.com/facebook/hermes/releases/download/v0.6.0/hermes-cli-darwin-v0.6.0.tar.gz
✔ Download completed.
❯ Extracting…
Installing binary to ~/.jsvu/engines/hermes-0.6.0/hermes-0.6.0…
Installing symlink at ~/.jsvu/hermes-0.6.0 pointing to ~/.jsvu/engines/hermes-0.6.0/hermes-0.6.0…
Installing binary to ~/.jsvu/engines/hermes-0.6.0/hermes-0.6.0-repl…
(node:28368) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, stat '/private/var/folders/zn/5lwc_xx93_34xxmqcc3y2xsc00fj2f/T/b79e840c97640ef031205c9bd8abfc2f/hermes-repl'
    at Object.statSync (fs.js:1009:3)
    at Object.statSync (/Users/mathiasb/.nvm/versions/node/v12.17.0/lib/node_modules/jsvu/node_modules/graceful-fs/polyfills.js:307:34)
    at getStatsSync (/Users/mathiasb/.nvm/versions/node/v12.17.0/lib/node_modules/jsvu/node_modules/fs-extra/lib/util/stat.js:58:18)
    at Object.checkPathsSync (/Users/mathiasb/.nvm/versions/node/v12.17.0/lib/node_modules/jsvu/node_modules/fs-extra/lib/util/stat.js:90:33)
    at Object.moveSync (/Users/mathiasb/.nvm/versions/node/v12.17.0/lib/node_modules/jsvu/node_modules/fs-extra/lib/move-sync/move-sync.js:14:28)
    at installSingleBinary (/Users/mathiasb/.nvm/versions/node/v12.17.0/lib/node_modules/jsvu/shared/installer.js:30:6)
    at Installer.installBinary (/Users/mathiasb/.nvm/versions/node/v12.17.0/lib/node_modules/jsvu/shared/installer.js:75:5)
    at /Users/mathiasb/.nvm/versions/node/v12.17.0/lib/node_modules/jsvu/engines/hermes/extract.js:37:15
(node:28368) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:28368) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by mathiasbynens** [comment]
Previous versions of hermes had `hermes-repl` for the REPL and `hermes` for the compiler. (https://github.com/facebook/hermes/issues/17#issuecomment-510850808)

Starting with v0.6.0, it looks like the REPL is now called `hermes`, and the compiler is now `hermesc`.
